#!/bin/sh
cd ~/notes
find * -type f | dmenu -p 'notes' | while read -r note; do
	nohup \
		alacritty --title 'notes-terminal-window' -e \
		vim +"set lines=26 columns=88" ~/notes/"$note" \
		>/dev/null 2>&1 &
done
