#!/bin/sh

export SUDO_ASKPASS=/tmp/shutdown-askpass.sh


echo '#!/bin/sh
echo "SETDESC Please enter password to shutdown system
SETPROMPT Password:
SETTITLE Sudo password for system shutdown
GETPIN" | pinentry | grep -E "^D " | sed "s/^D //"' > $SUDO_ASKPASS
chmod +x $SUDO_ASKPASS

sudo -A shutdown -h now
