#!/bin/bash

if [ "$UID" -ne 0 ]; then
	echo "Please run this as root!" >&2
	exit 6
fi

cd `dirname $0`

git submodule update --init || (echo "Submodule update failed!"; exit 5)

# Source inst and diff function
. ./utils/inst

# Load if we force changes (implies no interaction)
[ "$1" = "-f" ] && FORCE=true || FORCE=false

#################################################################################

if ask "System PATH profile"; then
	inst system/etc/profile.d/path.sh /etc/profile.d/path.sh
fi

if ask "X11 configuration"; then
	inst system/etc/X11/ /etc/X11/
fi

if ask "System-wide PulseAudio configuration"; then
	inst system/etc/pulse/ /etc/pulse/
fi

if ask "Wpa supplicant"; then
	# TODO
	true
fi

# As final step just ensure that correct user is owning system files
chown -R $(stat -c "%U:%G" "$0") system
