#!/bin/sh
#
# 10sleep: lock i3 season before suspend

case "$1" in
	hibernate|suspend)
		for socket in `find /run/user/*/i3 -name ipc-socket*`; do
			i3-msg -s $socket "exec i3lock -d -c 000000"
		done
	;;
	*) exit $NA
	;;
esac
