#!/home/cynerd/.local/sbin/user-service.sh
# vim: ft=sh

description="Mail synchronization tool"
pidfile="/tmp/syncemail-$(id -u).pid"

status() {
	[ -f $pidfile ] || return 1
	kill -0 "$(cat $pidfile)" || return 1
}

start() {
	true
	#~/.local/sbin/syncemail
}

stop() {
	PID="$(cat $pidfile)"
	kill $PID 2>/dev/null
	while kill -0 $PID 2>/dev/null; do sleep 1; done
}
