#!/home/cynerd/.local/sbin/user-service.sh
# vim: ft=sh

description="Mail synchronization tool"
pidfile="/tmp/syncemail-$(id -u).pid"

status() {
	[ -f $pidfile ] || return 1
	kill -0 "$(cat $pidfile)" || return 1
}

start() {
	~/.local/sbin/syncemail
}

stop() {
	kill "$(cat $pidfile)"
	wait "$(cat $pidfile)"
}
