#!/home/cynerd/.local/sbin/user-service.sh
# vim: ft=sh

description="Syncthing is an open, trustworthy and decentralized cloud storage system"
pidfile="/tmp/syncthing-$USER.pid"
logfile="/var/log/syncthing-$USER.log"

status() {
	[ -f $pidfile ] || return 1
	kill -0 "$(cat $pidfile)" || return 1
}

start() {
	start-stop-daemon -S -bmp $pidfile -1 $logfile -2 $logfile -- syncthing -no-browser
}

stop() {
	start-stop-daemon -K -p $pidfile -x syncthing
}
