# Configuration for Alacritty, the GPU enhanced terminal emulator.

env:
  # This is to support dircolors. For now dircolors does not support alacritty.
  TERM: xterm-256color

window:
  gtk_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 3

font:
  size: 8

colors:
   primary:
     background: '#000000'
     foreground: '#ffffff'
   normal:
     black:   '#000000'
     red:     '#cd0000'
     green:   '#00cd00'
     yellow:  '#cdcd00'
     blue:    '#6060ee'
     magenta: '#cd00cd'
     cyan:    '#00cdcd'
     white:   '#e5e5e5'
   bright:
     black:   '#7f7f7f'
     red:     '#ff0000'
     green:   '#00ff00'
     yellow:  '#ffff00'
     blue:    '#5c5cff'
     magenta: '#ff00ff'
     cyan:    '#00ffff'
     white:   '#ffffff'
  #search:
    # Allowed values are CellForeground and CellBackground, which reference the
    # affected cell, or hexadecimal colors like #ff00ff.
    #matches:
    #  foreground: '#000000'
    #  background: '#ffffff'
    #bar:
    #  background: '#c5c8c6'
    #  foreground: '#1d1f21'
  #selection:
  #  text: CellBackground
  #  background: CellForeground


#selection:
  #semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  #save_to_clipboard: false

#mouse:
#  hide_when_typing: true

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }
