#!/bin/bash

cd ~/.mail

if [ -f notify-notified ]; then
	NOTIFIED=`cat notify-notified`
	rm notify-notified
fi

for account in `ls`; do
	if cd "$account"/INBOX/new; then
		for m in `ls`; do
			echo $m
			echo $m >> ~/.mail/notify-notified
			if echo "$NOTIFIED" | grep "$m" >/dev/null; then continue; fi
			FROM=`grep -E "^From: " "$m" | sed 's/^From: //'`
			SUBJECT=`grep -E "^Subject: " "$m" | sed 's/^Subject: //'`
			notify-send "Email: $account" "$FROM: $SUBJECT"
		done
	fi
	cd ~/.mail
done
